"""Pydantic models for singleton central plan domain."""

from datetime import datetime
from typing import Any

from pydantic import BaseModel, ConfigDict, Field, field_validator


class CheckpointRecord(BaseModel):
    """Checkpoint summary for premium follow-up cadence."""

    checkpoint_at: datetime = Field(default_factory=datetime.now)
    summary: str = Field(..., min_length=1)
    ai_assessment: str | None = None
    decision: str | None = None
    next_step: str | None = None


class PlanStrategy(BaseModel):
    """Strategic intent and boundaries for the active plan."""

    primary_goal: str = Field(..., min_length=1)
    success_criteria: list[str] = Field(default_factory=list)
    constraints: list[str] = Field(default_factory=list)
    coaching_rationale: str = Field(..., min_length=1)
    adaptation_policy: str = Field(..., min_length=1)


class PlanExecution(BaseModel):
    """Operational, day-to-day plan structure."""

    today_training: dict[str, Any] = Field(default_factory=dict)
    today_nutrition: dict[str, Any] = Field(default_factory=dict)
    upcoming_days: list[Any] = Field(default_factory=list)
    active_focus: str = Field(..., min_length=1)
    current_risks: list[str] = Field(default_factory=list)
    pending_changes: list[dict[str, Any]] = Field(default_factory=list)


class PlanContextExerciseContext(BaseModel):
    """Exercise-level context to enrich coaching instructions."""

    exercise_name: str = Field(..., min_length=1)
    prescribed_sets: str | None = None
    prescribed_reps: str | None = None
    load_guidance: str | None = None
    last_load_kg: float | None = None
    last_load_text: str | None = None
    last_performed_at: str | None = None


class PlanContextAdherence7D(BaseModel):
    """Compact 7-day adherence block for training and nutrition."""

    training_percent: int | None = Field(default=None, ge=0, le=100)
    nutrition_percent: int | None = Field(default=None, ge=0, le=100)
    window_start: str = Field(..., min_length=1)
    window_end: str = Field(..., min_length=1)


class PlanContextWeightTrend(BaseModel):
    """Weekly weight trend context attached to plan snapshot."""

    value_kg_per_week: float
    source: str = Field(..., min_length=1)


class PlanPromptContext(BaseModel):
    """Compact and prompt-safe active plan context."""

    title: str = Field(..., min_length=1)
    objective_summary: str = Field(..., min_length=1)
    plan_period: str = Field(..., min_length=1)
    active_focus: str = Field(..., min_length=1)
    today_training: str = Field(..., min_length=1)
    today_nutrition: str = Field(..., min_length=1)
    upcoming_days: list[str] = Field(default_factory=list)
    today_training_context: list[PlanContextExerciseContext] = Field(
        default_factory=list,
    )
    adherence_7d: PlanContextAdherence7D | None = None
    weight_trend_weekly: PlanContextWeightTrend | None = None
    last_checkpoint_summary: str | None = None
    critical_constraints: list[str] = Field(default_factory=list)


class PlanUpsertInput(BaseModel):
    """Payload generated by AI to create or update singleton plan."""

    title: str = Field(..., min_length=1)
    objective_summary: str = Field(..., min_length=1)
    change_reason: str = Field(..., min_length=1)
    strategy: dict[str, Any]
    execution: dict[str, Any]
    checkpoints: list[CheckpointRecord] = Field(default_factory=list)


class UserPlan(BaseModel):
    """Full persisted singleton plan payload."""

    id: str | None = Field(default=None)
    user_email: str = Field(..., min_length=3)
    title: str = Field(..., min_length=1)
    objective_summary: str = Field(..., min_length=1)
    start_date: datetime
    end_date: datetime
    strategy: PlanStrategy
    execution: PlanExecution
    checkpoints: list[CheckpointRecord] = Field(default_factory=list)
    change_reason: str | None = None
    created_at: datetime = Field(default_factory=datetime.now)
    updated_at: datetime = Field(default_factory=datetime.now)

    @field_validator("end_date")
    @classmethod
    def validate_dates(cls, end_date: datetime, info):
        """Ensure range is valid and explicit."""
        start_date = info.data.get("start_date")
        if start_date and end_date < start_date:
            raise ValueError("end_date must be greater than or equal to start_date")
        return end_date


class UserPlanWithId(UserPlan):
    """Active plan with MongoDB id alias."""

    id: str = Field(..., validation_alias="_id")

    model_config = ConfigDict(populate_by_name=True)
