"""Pydantic models for the central coaching plan domain."""

from datetime import datetime
from enum import Enum
from typing import Any

from pydantic import BaseModel, ConfigDict, Field, field_validator


class PlanStatus(str, Enum):
    """Supported states for plan lifecycle."""

    DRAFT = "draft"
    AWAITING_APPROVAL = "awaiting_approval"
    ACTIVE = "active"
    ADJUSTMENT_PENDING_APPROVAL = "adjustment_pending_approval"
    COMPLETED = "completed"
    ARCHIVED = "archived"


class PlanApprovalRequest(BaseModel):
    """Explicit approval payload that the user must confirm."""

    requested_at: datetime = Field(default_factory=datetime.now)
    summary: str = Field(..., min_length=1)
    requested_by: str = Field(default="ai")


class CheckpointRecord(BaseModel):
    """Checkpoint summary for premium follow-up cadence."""

    checkpoint_at: datetime = Field(default_factory=datetime.now)
    summary: str = Field(..., min_length=1)
    ai_assessment: str | None = None
    decision: str | None = None
    next_step: str | None = None


class PlanStrategy(BaseModel):
    """Strategic intent and boundaries for the active plan."""

    primary_goal: str = Field(..., min_length=1)
    success_criteria: list[str] = Field(default_factory=list)
    constraints: list[str] = Field(default_factory=list)
    coaching_rationale: str = Field(..., min_length=1)
    adaptation_policy: str = Field(..., min_length=1)


class PlanExecution(BaseModel):
    """Operational, day-to-day plan structure."""

    today_training: dict[str, Any] = Field(default_factory=dict)
    today_nutrition: dict[str, Any] = Field(default_factory=dict)
    upcoming_days: list[Any] = Field(default_factory=list)
    active_focus: str = Field(..., min_length=1)
    current_risks: list[str] = Field(default_factory=list)
    pending_changes: list[dict[str, Any]] = Field(default_factory=list)


class PlanTracking(BaseModel):
    """Progress and adherence signals used by AI coaching."""

    checkpoints: list[CheckpointRecord] = Field(default_factory=list)
    adherence_snapshot: dict[str, Any] = Field(default_factory=dict)
    progress_snapshot: dict[str, Any] = Field(default_factory=dict)
    last_ai_assessment: str | None = None
    last_user_acknowledgement: datetime | None = None


class PlanGovernance(BaseModel):
    """Version-change context and approval metadata."""

    change_reason: str | None = None
    approval_request: PlanApprovalRequest | None = None


class PlanSnapshot(BaseModel):
    """Compact and prompt-safe active plan context."""

    title: str = Field(..., min_length=1)
    objective_summary: str = Field(..., min_length=1)
    status: str = Field(..., min_length=1)
    active_focus: str = Field(..., min_length=1)
    today_training: str = Field(..., min_length=1)
    today_nutrition: str = Field(..., min_length=1)
    upcoming_days: list[str] = Field(default_factory=list)
    last_checkpoint_summary: str | None = None
    critical_constraints: list[str] = Field(default_factory=list)
    pending_adjustment: str | None = None


class PlanProposalInput(BaseModel):
    """Payload generated by AI whenever it proposes a plan version."""

    title: str = Field(..., min_length=1)
    objective_summary: str = Field(..., min_length=1)
    change_reason: str = Field(..., min_length=1)
    strategy: dict[str, Any]
    execution: dict[str, Any]
    tracking: dict[str, Any]


class ActivePlan(BaseModel):
    """Full persisted active-plan payload."""

    id: str | None = Field(default=None)
    user_email: str = Field(..., min_length=3)
    status: PlanStatus
    title: str = Field(..., min_length=1)
    objective_summary: str = Field(..., min_length=1)
    start_date: datetime
    end_date: datetime
    version: int = Field(..., ge=1)
    strategy: PlanStrategy
    execution: PlanExecution
    tracking: PlanTracking
    governance: PlanGovernance
    created_at: datetime = Field(default_factory=datetime.now)
    updated_at: datetime = Field(default_factory=datetime.now)

    @field_validator("end_date")
    @classmethod
    def validate_dates(cls, end_date: datetime, info):
        """Ensure range is valid and explicit."""
        start_date = info.data.get("start_date")
        if start_date and end_date < start_date:
            raise ValueError("end_date must be greater than or equal to start_date")
        return end_date


class ActivePlanWithId(ActivePlan):
    """Active plan with MongoDB id alias."""

    id: str = Field(..., validation_alias="_id")

    model_config = ConfigDict(populate_by_name=True)
