"""Plan domain service helpers for prompt context and orchestration."""

from datetime import date, datetime, timedelta

from src.api.models.plan import (
    UserPlan,
    PlanUpsertInput,
    PlanPromptContext,
    PlanContextAdherence7D,
    PlanContextExerciseContext,
    PlanContextWeightTrend,
)

REQUIRED_INTAKE_FIELDS = (
    "dias_disponiveis_treino",
    "frequencia_treino_semana",
    "nivel_treinamento",
    "restricoes_lesoes",
    "tempo_por_sessao_min",
    "preferencia_ambiente",
)


def missing_intake_fields(strategy: dict) -> list[str]:
    """Return missing mandatory discovery fields required for plan creation."""
    return [field for field in REQUIRED_INTAKE_FIELDS if field not in strategy]


def missing_execution_fields(execution: dict) -> list[str]:
    """Return missing mandatory execution blocks required for an actionable plan."""
    def has_exercises(training_payload: object) -> bool:
        if not isinstance(training_payload, dict):
            return False
        session = training_payload.get("session")
        if isinstance(session, dict) and isinstance(session.get("exercises"), list):
            return len(session["exercises"]) > 0
        if isinstance(training_payload.get("exercises"), list):
            return len(training_payload["exercises"]) > 0
        return False

    missing: list[str] = []
    if not execution.get("today_training"):
        missing.append("today_training")
    if not execution.get("today_nutrition"):
        missing.append("today_nutrition")
    upcoming_days = execution.get("upcoming_days")
    if not upcoming_days:
        missing.append("upcoming_days")
    today_training = execution.get("today_training")
    if not has_exercises(today_training):
        missing.append("training_exercises")
    planned_days_missing_details = False
    if isinstance(upcoming_days, list):
        for day in upcoming_days:
            if not isinstance(day, dict):
                planned_days_missing_details = True
                break
            status = day.get("status")
            if status == "rest":
                continue
            if not has_exercises(day.get("training")):
                planned_days_missing_details = True
                break
    if planned_days_missing_details:
        missing.append("upcoming_training_exercises")
    return missing


def _merge_plan_sections(
    latest_plan: UserPlan | None,
    payload: PlanUpsertInput,
) -> tuple[dict, dict, list]:
    base_strategy = latest_plan.strategy.model_dump() if latest_plan else {}
    base_execution = latest_plan.execution.model_dump() if latest_plan else {}
    base_checkpoints = latest_plan.checkpoints if latest_plan else []
    strategy_data = {**base_strategy, **payload.strategy}
    execution_data = {**base_execution, **payload.execution}
    checkpoints = payload.checkpoints if payload.checkpoints else base_checkpoints
    return strategy_data, execution_data, checkpoints


def build_plan_singleton(
    user_email: str,
    latest_plan: UserPlan | None,
    payload: PlanUpsertInput,
) -> UserPlan:
    """Builds the singleton plan payload."""
    now = datetime.now()
    strategy_data, execution_data, checkpoints = _merge_plan_sections(
        latest_plan, payload
    )

    start_date = latest_plan.start_date if latest_plan else now
    if latest_plan and latest_plan.end_date > latest_plan.start_date:
        end_date = latest_plan.end_date
    else:
        end_date = start_date + timedelta(days=27)

    return UserPlan(
        user_email=user_email,
        title=payload.title,
        objective_summary=payload.objective_summary,
        start_date=start_date,
        end_date=end_date,
        strategy={
            "primary_goal": strategy_data.get("primary_goal", "unspecified"),
            "success_criteria": strategy_data.get("success_criteria", []),
            "constraints": strategy_data.get("constraints", []),
            "coaching_rationale": strategy_data.get(
                "coaching_rationale", "generated by ai"
            ),
            "adaptation_policy": strategy_data.get(
                "adaptation_policy", "ai_managed_continuous"
            ),
        },
        execution={
            "today_training": execution_data.get("today_training", {}),
            "today_nutrition": execution_data.get("today_nutrition", {}),
            "upcoming_days": execution_data.get("upcoming_days", []),
            "active_focus": execution_data.get("active_focus", "consistencia"),
            "current_risks": execution_data.get("current_risks", []),
            "pending_changes": execution_data.get("pending_changes", []),
        },
        checkpoints=checkpoints,
        change_reason=payload.change_reason,
    )


def _extract_today_training(execution: dict) -> str:
    training = _resolve_today_training_payload(execution)
    if isinstance(training, dict):
        return str(training.get("title") or training.get("summary") or "Nao definido")
    return str(training) if training else "Nao definido"


def _parse_iso_date(value: object) -> date | None:
    if isinstance(value, datetime):
        return value.date()
    if isinstance(value, date):
        return value
    if isinstance(value, str):
        try:
            return datetime.fromisoformat(value.replace("Z", "+00:00")).date()
        except ValueError:
            return None
    return None


def _is_training_like(payload: object) -> bool:
    if isinstance(payload, str):
        return bool(payload.strip())
    if not isinstance(payload, dict):
        return False

    has_title = isinstance(payload.get("title"), str) and payload.get("title").strip()
    has_summary = isinstance(payload.get("summary"), str) and payload.get("summary").strip()
    has_session_exercises = False
    session = payload.get("session")
    if isinstance(session, dict) and isinstance(session.get("exercises"), list):
        has_session_exercises = len(session["exercises"]) > 0
    has_direct_exercises = isinstance(payload.get("exercises"), list) and len(
        payload["exercises"]
    ) > 0
    return bool(
        has_title or has_summary or has_session_exercises or has_direct_exercises
    )


def _resolve_today_training_payload(
    execution: dict, reference_date: date | None = None
) -> object:
    today = reference_date or datetime.now().date()
    upcoming_days = execution.get("upcoming_days")
    if isinstance(upcoming_days, list):
        for item in upcoming_days:
            if not isinstance(item, dict):
                continue
            if item.get("status") == "rest":
                continue
            if _parse_iso_date(item.get("date")) != today:
                continue
            candidate = item.get("training")
            if _is_training_like(candidate):
                return candidate
    return execution.get("today_training", {})


def _extract_upcoming_days(execution: dict, reference_date: date | None = None) -> list[str]:
    today = reference_date or datetime.now().date()
    upcoming_days = execution.get("upcoming_days")
    if not isinstance(upcoming_days, list):
        return []

    normalized: list[str] = []
    for item in upcoming_days:
        if isinstance(item, dict):
            item_date = _parse_iso_date(item.get("date"))
            if item_date is not None and item_date <= today:
                continue
        normalized.append(str(item))
    return normalized


def _extract_today_nutrition(execution: dict) -> str:
    nutrition = execution.get("today_nutrition", {})
    if isinstance(nutrition, dict):
        calories = nutrition.get("calories")
        protein = nutrition.get("protein_target")
        if calories is not None or protein is not None:
            return f"{calories or '-'} kcal / {protein or '-'}g proteina"
    return str(nutrition) if nutrition else "Nao definido"


def build_plan_prompt_snapshot(
    plan: UserPlan | None,
    *,
    today_training_context: list[PlanContextExerciseContext] | None = None,
    adherence_7d: PlanContextAdherence7D | None = None,
    weight_trend_weekly: PlanContextWeightTrend | None = None,
) -> PlanPromptContext | None:
    """Builds a compact snapshot from active plan payload."""
    if plan is None:
        return None

    checkpoints = plan.checkpoints
    last_checkpoint = checkpoints[-1].summary if checkpoints else None

    execution_payload = plan.execution.model_dump()

    return PlanPromptContext(
        title=plan.title,
        objective_summary=plan.objective_summary,
        plan_period=(
            f"{plan.start_date.strftime('%Y-%m-%d')} a "
            f"{plan.end_date.strftime('%Y-%m-%d')}"
        ),
        active_focus=plan.execution.active_focus,
        today_training=_extract_today_training(execution_payload),
        today_nutrition=_extract_today_nutrition(execution_payload),
        upcoming_days=_extract_upcoming_days(execution_payload),
        today_training_context=today_training_context or [],
        adherence_7d=adherence_7d,
        weight_trend_weekly=weight_trend_weekly,
        last_checkpoint_summary=last_checkpoint,
        critical_constraints=plan.strategy.constraints,
    )


def format_plan_snapshot(snapshot: PlanPromptContext | None) -> str:
    """Formats plan snapshot as a readable prompt block."""
    if snapshot is None:
        return (
            "Nenhum plano registrado.\n"
            "Acao obrigatoria: conduza discovery com o aluno e insista na coleta dos "
            "dados faltantes ate conseguir criar um plano completo de treino e nutricao."
        )

    upcoming = ", ".join(snapshot.upcoming_days) if snapshot.upcoming_days else "sem previsao"
    constraints = (
        ", ".join(snapshot.critical_constraints)
        if snapshot.critical_constraints
        else "sem restricoes criticas"
    )
    checkpoint = snapshot.last_checkpoint_summary or "sem checkpoint recente"
    training_context_lines: list[str] = []
    if snapshot.today_training_context:
        training_context_lines.append("Contexto do treino de hoje:")
        for item in snapshot.today_training_context:
            prescription = f"{item.prescribed_sets or '-'}x{item.prescribed_reps or '-'}"
            if item.last_load_kg is not None and item.last_performed_at:
                training_context_lines.append(
                    f"- {item.exercise_name}: {prescription} | ultima carga registrada "
                    f"{item.last_load_kg:.0f} kg em {item.last_performed_at}"
                )
            else:
                training_context_lines.append(
                    f"- {item.exercise_name}: {prescription} | "
                    "ultima carga registrada: indisponivel"
                )

    adherence_line = ""
    if snapshot.adherence_7d is not None:
        training_pct = (
            "indisponivel"
            if snapshot.adherence_7d.training_percent is None
            else f"{snapshot.adherence_7d.training_percent}%"
        )
        nutrition_pct = (
            "indisponivel"
            if snapshot.adherence_7d.nutrition_percent is None
            else f"{snapshot.adherence_7d.nutrition_percent}%"
        )
        adherence_line = f"Aderencia 7d: treino {training_pct} | nutricao {nutrition_pct}"

    trend_line = ""
    if snapshot.weight_trend_weekly is not None:
        trend_line = (
            "Tendencia de peso: "
            f"{snapshot.weight_trend_weekly.value_kg_per_week:+.2f} kg/semana"
        )

    enriched_sections = ""
    if training_context_lines:
        enriched_sections += "\\n".join(training_context_lines)
    if adherence_line:
        enriched_sections += f"\\n{adherence_line}"
    if trend_line:
        enriched_sections += f"\\n{trend_line}"

    return (
        f"Plano: {snapshot.title}\\n"
        f"Objetivo: {snapshot.objective_summary}\\n"
        f"Periodo do plano: {snapshot.plan_period}\\n"
        f"Foco atual: {snapshot.active_focus}\\n"
        f"Treino de hoje: {snapshot.today_training}\\n"
        f"{f'{enriched_sections}\\n' if enriched_sections else ''}"
        f"Nutricao de hoje: {snapshot.today_nutrition}\\n"
        f"Proximos dias: {upcoming}\\n"
        f"Ultimo checkpoint: {checkpoint}\\n"
        f"Restricoes criticas: {constraints}"
    )
