"""Plan domain service helpers for prompt context and orchestration."""

from datetime import datetime

from src.api.models.plan import ActivePlan, PlanSnapshot, PlanProposalInput, PlanStatus


def build_next_plan_version(
    user_email: str,
    latest_plan: ActivePlan | None,
    payload: PlanProposalInput,
    approval_summary: str | None = None,
) -> ActivePlan:
    """Builds the next plan version payload in awaiting_approval status."""
    now = datetime.now()
    version = 1 if latest_plan is None else latest_plan.version + 1

    base_strategy = latest_plan.strategy.model_dump() if latest_plan else {}
    base_execution = latest_plan.execution.model_dump() if latest_plan else {}
    base_tracking = latest_plan.tracking.model_dump() if latest_plan else {}

    strategy_data = {**base_strategy, **payload.strategy}
    execution_data = {**base_execution, **payload.execution}
    tracking_data = {**base_tracking, **payload.tracking}

    start_date = latest_plan.start_date if latest_plan else now
    end_date = latest_plan.end_date if latest_plan else now

    return ActivePlan(
        user_email=user_email,
        status=PlanStatus.AWAITING_APPROVAL,
        title=payload.title,
        objective_summary=payload.objective_summary,
        start_date=start_date,
        end_date=end_date,
        version=version,
        strategy={
            "primary_goal": strategy_data.get("primary_goal", "unspecified"),
            "success_criteria": strategy_data.get("success_criteria", []),
            "constraints": strategy_data.get("constraints", []),
            "coaching_rationale": strategy_data.get(
                "coaching_rationale", "generated by ai"
            ),
            "adaptation_policy": strategy_data.get(
                "adaptation_policy", "approval_required"
            ),
        },
        execution={
            "today_training": execution_data.get("today_training", {}),
            "today_nutrition": execution_data.get("today_nutrition", {}),
            "upcoming_days": execution_data.get("upcoming_days", []),
            "active_focus": execution_data.get("active_focus", "consistencia"),
            "current_risks": execution_data.get("current_risks", []),
            "pending_changes": execution_data.get("pending_changes", []),
        },
        tracking={
            "checkpoints": tracking_data.get("checkpoints", []),
            "adherence_snapshot": tracking_data.get("adherence_snapshot", {}),
            "progress_snapshot": tracking_data.get("progress_snapshot", {}),
            "last_ai_assessment": tracking_data.get("last_ai_assessment"),
            "last_user_acknowledgement": tracking_data.get(
                "last_user_acknowledgement"
            ),
        },
        governance={
            "change_reason": payload.change_reason,
            "approval_request": {
                "summary": approval_summary or payload.change_reason,
                "requested_at": now,
                "requested_by": "ai",
            },
        },
    )


def _extract_today_training(execution: dict) -> str:
    training = execution.get("today_training", {})
    if isinstance(training, dict):
        return str(training.get("title") or training.get("summary") or "Nao definido")
    return str(training) if training else "Nao definido"


def _extract_today_nutrition(execution: dict) -> str:
    nutrition = execution.get("today_nutrition", {})
    if isinstance(nutrition, dict):
        calories = nutrition.get("calories")
        protein = nutrition.get("protein_target")
        if calories is not None or protein is not None:
            return f"{calories or '-'} kcal / {protein or '-'}g proteina"
    return str(nutrition) if nutrition else "Nao definido"


def build_plan_prompt_snapshot(plan: ActivePlan | None) -> PlanSnapshot | None:
    """Builds a compact snapshot from active plan payload."""
    if plan is None:
        return None

    checkpoints = plan.tracking.checkpoints
    last_checkpoint = checkpoints[-1].summary if checkpoints else None
    pending_adjustment = None
    if plan.governance.approval_request is not None:
        pending_adjustment = plan.governance.approval_request.summary

    return PlanSnapshot(
        title=plan.title,
        objective_summary=plan.objective_summary,
        status=plan.status.value,
        active_focus=plan.execution.active_focus,
        today_training=_extract_today_training(plan.execution.model_dump()),
        today_nutrition=_extract_today_nutrition(plan.execution.model_dump()),
        upcoming_days=[str(item) for item in plan.execution.upcoming_days],
        last_checkpoint_summary=last_checkpoint,
        critical_constraints=plan.strategy.constraints,
        pending_adjustment=pending_adjustment,
    )


def format_plan_snapshot(snapshot: PlanSnapshot | None) -> str:
    """Formats plan snapshot as a readable prompt block."""
    if snapshot is None:
        return ""

    upcoming = ", ".join(snapshot.upcoming_days) if snapshot.upcoming_days else "sem previsao"
    constraints = (
        ", ".join(snapshot.critical_constraints)
        if snapshot.critical_constraints
        else "sem restricoes criticas"
    )
    checkpoint = snapshot.last_checkpoint_summary or "sem checkpoint recente"
    pending = snapshot.pending_adjustment or "nenhum"

    return (
        f"Plano ativo: {snapshot.title}\\n"
        f"Objetivo: {snapshot.objective_summary}\\n"
        f"Status: {snapshot.status}\\n"
        f"Foco atual: {snapshot.active_focus}\\n"
        f"Treino de hoje: {snapshot.today_training}\\n"
        f"Nutricao de hoje: {snapshot.today_nutrition}\\n"
        f"Proximos dias: {upcoming}\\n"
        f"Ultimo checkpoint: {checkpoint}\\n"
        f"Restricoes criticas: {constraints}\\n"
        f"Ajuste pendente: {pending}"
    )
